using LazurdIT.FluentOrm.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlazorApp3.Shared
{
    [FluentTable("Movie")]
    public class Movie : IFluentModel
    {
        [FluentField(name: "MovieId", autoGenerated: true, isPrimary: true, allowNull: false)]
        public int MovieId { get; set; }

        [FluentField(name: "Title", allowNull: false)]
        public string Title { get; set; } = string.Empty;

        [FluentField(name: "Description", allowNull: false)]
        public string Description { get; set; }

        public override string ToString()
        {
            return ($"Id : {MovieId} , Title: {Title} , Description : {Description} ");
        }
    }
}
